### ISSUE TITLE
Can I ask about gams_indoor.csv?

### ISSUE THREAD

**Issue by wnsh0566** [twairball/gams-dataset#1]
I saw gams_indoor.csv file. and then I have a question about where did you measure this number?
Is it in indoor like home or office?  I'd like to use dataset for academical purpose. Can I use it?
thank you
have a good time

**Comment by twairball** [comment]
Academic use is allowed - please see README about attribution. 

data is measured indoors such as home or office.

**Comment by en-ashay** [comment]
@twairball Can you share approximately how many offices and houses data was collected from Shanghai district?
